### ISSUE TITLE
Removing Login and Register pages

### ISSUE THREAD

**Issue by aburmals** [app-generator/flask-argon-dashboard#5]
Can you help me with removing the Login and Register pages from this template?

**Comment by rosoftdeveloper** [comment]
Hello @aburmals, 

Thanks for using our products. At first look, this is not a product issue. Feel free to join the community on [Discord](https://discord.gg/fZC6hup) and request help from the support team or from the community. 

I will close this issue.

**Comment by aburmals** [comment]
Thank you Team Creative-Tim

Regards,
Haribalaji A

**Comment by app-generator** [comment]
:) We are not part of Creative-Tim. We are [partners](https://appseed.us/PARTNERS) indeed, but AppSeed is a standalone business. 

See u @aburmals
